name: scientific_computing
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.1
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.8
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blosc=1.21.6
  - bokeh=3.7.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.17.1
  - ca-certificates=2025.7.14
  - cffi=1.17.1
  - click=8.2.1
  - cloudpickle=3.1.1
  - comm=0.2.2
  - contourpy=1.3.2
  - cytoolz=1.0.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fsspec=2025.5.1
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.2.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.4
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.6
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=20.0.0
  - libpng=1.6.49
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - line_profiler=4.2.0
  - llvm-openmp=20.1.6
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.4.4
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - msgpack-python=1.1.1
  - narwhals=1.43.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - numba=0.61.2
  - numexpr=2.10.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.1
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.3.0
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - platformdirs=4.3.8
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pyarrow-core=20.0.0
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - pytables=3.10.2
  - python=3.13.3
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - re2=2024.07.02
  - readline=8.2
  - six=1.17.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - stack_data=0.6.3
  - tblib=3.1.0
  - tk=8.6.13
  - toolz=1.0.0
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - wcwidth=0.2.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - alabaster==1.0.0
      - babel==2.17.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - colorama==0.4.6
      - cycler==0.12.1
      - dask==2025.7.0
      - distributed==2025.7.0
      - docutils==0.21.2
      - euler-solver==0.1.0
      - fonttools==4.58.2
      - git-filter-repo==2.47.0
      - h5py==3.14.0
      - idna==3.10
      - imagesize==1.4.1
      - iniconfig==2.1.0
      - kiwisolver==1.4.8
      - mandelbrot-solver==0.1.0
      - mando==0.7.1
      - matplotlib==3.10.3
      - pluggy==1.6.0
      - pudb==2025.1
      - pyarrow==20.0.0
      - pyparsing==3.2.3
      - pytest==8.4.0
      - python-json-logger==2.0.7
      - radon==6.0.1
      - requests==2.32.4
      - roman-numerals-py==3.1.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - structlog==21.5.0
      - urllib3==2.4.0
      - urwid==3.0.2
      - urwid-readline==0.15.1
